replicaCount: 1

image:
  repository: dockerregistry.irddb.gov.np:5000/tp-itaxservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIp
  port: 6288

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - registrycreden
