replicaCount: 2

image:
  repository: dockerregistry.irddb.gov.np:5000/tp-itaxservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6288

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: []

# Name of Kubernetes secret for private registry
imagePullSecrets:
  - registrycreden

# Add ServiceAccount settings
serviceAccount:
  create: true
  name: "itaxservice-service"
